PizzaBoxSolution/PizzaBoxClient/Controllers/SignInOrUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PizzaBoxData;
using PizzaBoxDomain;

namespace PizzaBoxClient.Controllers
{
    public class SignInOrUpController : Controller
    {
        private readonly IRepository db;

        Models.CustomerModel cust = new Models.CustomerModel();
        List<Models.CustomerModel> custlist = new List<Models.CustomerModel>();

        Pizza p = new Pizza();
        Customer c = new Customer();

        public SignInOrUpController(IRepository db)
        {
            this.db = db;
        }
        // GET: SignInOrUp
        public ActionResult LogIn()
        {
            TempData["custid"] = "-1";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(IFormCollection collection, Models.CustomerModel cust)
        {
            
            var customer = db.GetCustomers();
            foreach (var i in customer)
            {
                if (i.Username == cust.Username)
                {
                    if (i.Password == cust.Password)
                    {
                        var user = db.GetCustomerByUser(i.Username);
                        c.Username = i.Username;
                        c.Password = i.Password;

                        c.FirstName = i.FirstName;
                        c.LastName = i.LastName;
                        c.Add1 = i.Add1;
                        c.Add2 = i.Add2;
                        c.City = i.City;
                        c.State = i.State;
                        c.Country = i.Country;
                        c.ZipCode = i.ZipCode;

                        c.CustID = i.CustID;

                        TempData["custid"] = c.CustID;

                        return RedirectToAction("Locations", "Home");
                    }
                    ViewData["Text"] = "Incorrect Password.";
                    return View();
                }
            }

            ViewData["Text"] = "Username does not exist.";
            return View();
        }

        // G: SignInOrUp/Create
        public ActionResult CreateAccount()
        {
            return View();
        }

        // POST: SignInOrUp/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAccount(IFormCollection collection, Models.CustomerModel cust)
        {
            Customer c = new Customer();
            bool usernametaken = false;

            var customers = db.GetCustomers();

            foreach (var i in customers)
            {
                if (i.Username == cust.Username)
                {
                    usernametaken = true;
                }
            }
            if (usernametaken == true)
            {
                ViewData["Text"] = "Username is taken.";
                return View(); //include error catcher
            }
            else
            {
                c.Username = cust.Username;
            }
            if (c.MatchPassword(cust.Password, cust.ReEnterPassword) == true)
            {
                c.Password = cust.Password;
            }
            else
            {
                ViewData["Text"] = "Passwords do not match.";
                return View(); //include error catcher
            }

            c.FirstName = cust.FirstName;
            c.LastName = cust.LastName;
            c.Add1 = cust.Add1;
            c.Add2 = cust.Add2;
            c.City = cust.City;
            c.State = cust.State;
            c.Country = cust.Country;
            c.ZipCode = cust.ZipCode;

            try
            {
                db.AddCustomer(c);
                db.Save();
                c.CustID = db.GetCustomerByUser(cust.Username).CustID;
                TempData["custid"] = c.CustID;
                return RedirectToAction("Locations", "Home");
            }
            catch
            {
                return RedirectToAction("LogIn");
            }
        }
    }
}

PizzaBoxSolution/PizzaBoxClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaBoxWebClient</title>

    <environment include="Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Production">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="SignInOrUp" asp-action="LogIn">
                    <img src="~/pizzapanda.png" width="100" height="100" alt="pizza panda">
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="SignInOrUp" asp-action="LogIn">Pizza Paradise</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SignInOrUp" asp-action="LogIn">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SignInOrUp" asp-action="CreateAccount">Create An Account</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PizzaBoxWebClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

PizzaBoxSolution/PizzaBoxClient/Views/Shared/_LayoutAfter.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaBoxWebClient</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Locations">
                    <img src="~/pizzapanda.png" width="100" height="100" alt="pizza panda">
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Locations">Pizza Paradise</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Locations">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="PlaceOrder">Place Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="RedirectToViewOrders">View Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ViewRestaurantData">View Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SignInOrUp" asp-action="LogIn">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PizzaBoxWebClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>